// Configuración de Supabase - NO COMMITAR a repositorio público
const SUPABASE_URL = "https://lzhwfchgrhaoxmgemdto.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6aHdmY2hncmhhb3htZ2VtZHRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODYwNDksImV4cCI6MjA2ODI2MjA0OX0.MRNrDTLu62ybHVlm_cytfqqe1SxhEtndcQyavIdIZ00";